### PR TITLE
Add appveyor CI config

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma/issues/41

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 build is failing due to AppVeyor?

**Comment by CAMOBAP795** [comment]
@ronaldtse tests failed, I will have a look

**Comment by opoudjis** [comment]
Given how heavily in flux this gem is (it is being reengineered in a different branch), I am not surprised. Do alert @abunashir though.

**Comment by CAMOBAP795** [comment]
Missing `xml2rfc` on windows, looking how to add it

**Comment by CAMOBAP795** [comment]
In progress

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis ready for review

**Comment by CAMOBAP795** [comment]
Looks like still some instability in test exists, investigating

**Comment by ronaldtse** [comment]
@CAMOBAP795 OK, ping me when ready. Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse ready for review

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Pull request merged**
