### PR TITLE
Feature/use vcr

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #21

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 specs still failing.

**Comment by opoudjis** [comment]
I'll note that on my Mac, rspec has been failing on this gem for a little while, on the generation of RFC XML for examples: 

````
      Failure/Error: expect(system("xml2rfc #{old_xml}.1 -o #{old_xml}.txt")).to be_truthy
      
        expected: truthy value
             got: nil
````

This isn't happening in Travis though, and is not the error being reported.

FWIW, I'm ok with the changes.

**Comment by ronaldtse** [comment]
@CAMOBAP795 the particular failure is on Ruby 2.4/2.5 on Mac:

```
/Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/yaml.rb:5: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
LoadError: dlopen(/Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle, 9): Library not loaded: /Users/travis/.rvm/rubies/ruby-2.5.4/lib/libruby.2.5.dylib
  Referenced from: /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle
  Reason: image not found - /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle
Traceback (most recent call last):
	52: from /Users/travis/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
	51: from /Users/travis/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
	50: from /Users/travis/.rvm/gems/ruby-2.5.5/bin/bundle:23:in `<main>'
	49: from /Users/travis/.rvm/gems/ruby-2.5.5/bin/bundle:23:in `load'
	48: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
	47: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	46: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
	45: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
	44: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	43: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
	42: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	41: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	40: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	39: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/cli.rb:234:in `install'
	38: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/settings.rb:144:in `temporary'
	37: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/cli.rb:235:in `block in install'
	36: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/cli/install.rb:65:in `run'
	35: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/installer.rb:25:in `install'
	34: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/installer.rb:73:in `run'
	33: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/process_lock.rb:9:in `lock'
	32: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/process_lock.rb:9:in `open'
	31: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/process_lock.rb:12:in `block in lock'
	30: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/installer.rb:84:in `block in run'
	29: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/installer.rb:310:in `resolve_if_needed'
	28: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/definition.rb:158:in `resolve_remotely!'
	27: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/definition.rb:170:in `specs'
	26: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/spec_set.rb:81:in `materialize'
	25: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/spec_set.rb:81:in `map!'
	24: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/spec_set.rb:84:in `block in materialize'
	23: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/lazy_specification.rb:76:in `__materialize__'
	22: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:89:in `specs'
	21: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:386:in `remote_specs'
	20: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/index.rb:11:in `build'
	19: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:387:in `block in remote_specs'
	18: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:251:in `fetchers'
	17: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:251:in `map'
	16: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:253:in `block in fetchers'
	15: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:253:in `new'
	14: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/fetcher.rb:85:in `initialize'
	13: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/fetcher.rb:242:in `connection'
	12: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:115:in `configuration'
	11: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	10: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/psyched_yaml.rb:18:in `<top (required)>'
	 8: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/yaml.rb:6:in `<top (required)>'
	 5: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 4: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.rb:13:in `<top (required)>'
	 2: from /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.rb:16:in `rescue in <top (required)>'
	 1: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': dlopen(/Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle, 9): Library not loaded: /Users/travis/.rvm/rubies/ruby-2.5.4/lib/libruby.2.5.dylib (LoadError)
  Referenced from: /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle
  Reason: image not found - /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle
The command "eval bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} " failed. Retrying, 2 of 3.
Your Gemfile lists the gem vcr (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once (per group).
While it's not a problem now, it could cause errors if you change the version of one of them later.
/Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/yaml.rb:5: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
LoadError: dlopen(/Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle, 9): Library not loaded: /Users/travis/.rvm/rubies/ruby-2.5.4/lib/libruby.2.5.dylib
  Referenced from: /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle
  Reason: image not found - /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle
Traceback (most recent call last):
	52: from /Users/travis/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
	51: from /Users/travis/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
	50: from /Users/travis/.rvm/gems/ruby-2.5.5/bin/bundle:23:in `<main>'
	49: from /Users/travis/.rvm/gems/ruby-2.5.5/bin/bundle:23:in `load'
	48: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
	47: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	46: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
	45: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
	44: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	43: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
	42: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	41: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	40: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	39: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/cli.rb:234:in `install'
	38: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/settings.rb:144:in `temporary'
	37: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/cli.rb:235:in `block in install'
	36: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/cli/install.rb:65:in `run'
	35: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/installer.rb:25:in `install'
	34: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/installer.rb:73:in `run'
	33: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/process_lock.rb:9:in `lock'
	32: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/process_lock.rb:9:in `open'
	31: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/process_lock.rb:12:in `block in lock'
	30: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/installer.rb:84:in `block in run'
	29: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/installer.rb:310:in `resolve_if_needed'
	28: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/definition.rb:158:in `resolve_remotely!'
	27: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/definition.rb:170:in `specs'
	26: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/spec_set.rb:81:in `materialize'
	25: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/spec_set.rb:81:in `map!'
	24: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/spec_set.rb:84:in `block in materialize'
	23: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/lazy_specification.rb:76:in `__materialize__'
	22: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:89:in `specs'
	21: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:386:in `remote_specs'
	20: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/index.rb:11:in `build'
	19: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:387:in `block in remote_specs'
	18: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:251:in `fetchers'
	17: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:251:in `map'
	16: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:253:in `block in fetchers'
	15: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:253:in `new'
	14: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/fetcher.rb:85:in `initialize'
	13: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/fetcher.rb:242:in `connection'
	12: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:115:in `configuration'
	11: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	10: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /Users/travis/.rvm/gems/ruby-2.5.5/gems/bundler-2.0.1/lib/bundler/psyched_yaml.rb:18:in `<top (required)>'
	 8: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/yaml.rb:6:in `<top (required)>'
	 5: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 4: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.rb:13:in `<top (required)>'
	 2: from /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.rb:16:in `rescue in <top (required)>'
	 1: from /Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/travis/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': dlopen(/Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle, 9): Library not loaded: /Users/travis/.rvm/rubies/ruby-2.5.4/lib/libruby.2.5.dylib (LoadError)
  Referenced from: /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle
  Reason: image not found - /Users/travis/build/metanorma/metanorma-ietf/vendor/bundle/ruby/2.5.0/gems/psych-3.1.0/lib/psych.bundle
The command "eval bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} " failed. Retrying, 3 of 3.
```

**Comment by CAMOBAP795** [comment]
@opoudjis can it be related to missing `xml2rfc` tool on your machine?

The issue on CI fixed, it was related to broken cache, now I think that maybe gem caching on CI isn't good idea

**Comment by ronaldtse** [comment]
@CAMOBAP795 the cassette is 35MB! It's seriously increasing the size of this repo. We don't want to include the entire XML library index. Can you tailor this down?

**Comment by ronaldtse** [comment]
Whatever code that is pulling the entire XML index needs serious fixing.

**Comment by opoudjis** [comment]
@CAMOBAP795 Doh! Yes, xml2rfc used to work, and now: "bash: /usr/local/bin/xml2rfc: /usr/local/opt/python3/bin/python3.6: bad interpreter: No such file or directory"

**Comment by CAMOBAP795** [comment]
> @CAMOBAP795 the cassette is 35MB! It's seriously increasing the size of this repo. We don't want to include the entire XML library index. Can you tailor this down?

I think yes, according to my understanding I can cut response (I will have a look at it today)

**Comment by CAMOBAP795** [comment]
@ronaldtse ready for review

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you also provide instructions on how to update VCR? In case the endpoint changes the response, we need to be aware. Thanks.

**Comment by CAMOBAP795** [comment]
@ronaldtse 

1. generally `vcr_cassettes` dir needs to be deleted & after this re-run test
2. BUT in this case, after steps above, I did the manual cleanup with regexps

**Pull request merged**
